Issue 24 add json metadata commit body
Nautilus-Cyberneering/git-queue pull request #106
Opened 2022-03-25 09:48 UTC by yeraydavidrodriguez

Resolves #24 

This will add JSON enforcing and parsing of the commit messages body, according to the following [JTDSchema](https://ajv.js.org/json-type-definition.html#jtdschematype):

```typescript
interface CommitBodyMetaData {
  job_number?: number
  job_commit?: string
}

interface CommitBodyData {
  namespace: "git-queue.commit-body"
  version: number
  metadata: CommitBodyMetaData
  payload: string
}

const CommitBodySchema: JTDSchemaType<CommitBodyData> = {
  properties: {
    namespace: {enum: ["git-queue.commit-body"]},
    version: {type: 'int32'},
    payload: {type: 'string'},
    metadata: {
      optionalProperties: {
        job_number: {type: 'int32'},
        job_commit: {type: 'string'}
      },
      additionalProperties: true
    }
  },
  additionalProperties: true
}
```

2022-03-25 13:37 UTC, josecelano commented
@yeraydavidrodriguez and I were discussing today if it makes sense to allow the user to add custom metadata.

Pros
- Users could add metadata without defining a new schema for their contents. Right now they could define a JSON schema with custom metadata and the body but it forces them to parse the message body.

Cons
- We have to change the API. We are likely to need an extra argument with an array of custom attributes/metadata.

What do you think @da2ce7?

I've just checked another service (AWS):

https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-using-send-message-with-attributes.html

We could have a simpler version like an array of key-value attributes (all of them being strings).

I personally think we should not implement it yet, but only consider that our current schema could change in the future to include this custom attriutes.

2022-04-04 13:13 UTC, da2ce7 requested changes
I have reviewed the commit history.  It seems that there has been two merges included in the commit history. Including merging in merge-conflicts and then fixing them in later commit.

I recommend you restage your work on-top of the git-queue master and create new commits.

In this way you can verify that the CI passes for every commit.

2022-04-05 09:23 UTC, yeraydavidrodriguez commented on .github/workflows/test.yml
> +          job_payload: '{\"field\": \"value\", \"state\": \"pending\"}'
Yes, you are right, Fixed.

2022-04-05 11:33 UTC, da2ce7 commented
@yeraydavidrodriguez  I have created a squashed commit for the changes that are included in this pull request https://github.com/Nautilus-Cyberneering/git-queue/pull/118

2022-04-12 16:29 UTC, josecelano approved these changes

2022-04-13 08:58 UTC, josecelano commented
Moved to a new PR: https://github.com/Nautilus-Cyberneering/git-queue/pull/118

2022-04-13 08:58 UTC, closed without merging